/* Generated by curve_gen.py. */

#if !defined(BLINKER_SEQ_H)
#define BLINKER_SEQ_H

#include "al.h"

#define BLINKER_SEQ_TPS        125U
#define BLINKER_SEQ_PEAK_FRAME 15U

static const u8 BLINKER_SEQ[] =
{
    0U, 0U, 1U, 2U, 4U, 7U, 10U, 13U, 17U, 22U, 27U, 32U,
    38U, 45U, 52U, 60U, 60U, 60U, 60U, 60U, 60U, 58U, 57U, 55U,
    53U, 52U, 50U, 48U, 47U, 45U, 44U, 42U, 41U, 40U, 38U, 37U,
    35U, 34U, 33U, 32U, 30U, 29U, 28U, 27U, 26U, 24U, 23U, 22U,
    21U, 20U, 19U, 18U, 17U, 16U, 15U, 15U, 14U, 13U, 12U, 11U,
    11U, 10U, 9U, 9U, 8U, 7U, 7U, 6U, 6U, 5U, 5U, 4U,
    4U, 3U, 3U, 2U, 2U, 2U, 2U, 1U, 1U, 1U, 1U, 0U,
    0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U,
    0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U,
    0U, 0U, 0U, 0U, 0U, 0U,
};

#endif // BLINKER_SEQ_H
