/* Generated by curve_gen.py. */

#if !defined(BLINKER_SEQ_H)
#define BLINKER_SEQ_H

#include "al.h"

#define BLINKER_SEQ_TPS        100U
#define BLINKER_SEQ_PEAK_FRAME 8U

static const u8 BLINKER_SEQ[] =
{
    0U, 2U, 6U, 14U, 25U, 39U, 56U, 77U, 100U, 100U, 100U, 100U,
    100U, 100U, 100U, 100U, 100U, 100U, 100U, 100U, 100U, 100U, 100U, 100U,
    100U, 94U, 88U, 82U, 77U, 71U, 66U, 61U, 56U, 52U, 47U, 43U,
    39U, 35U, 32U, 28U, 25U, 22U, 19U, 17U, 14U, 12U, 10U, 8U,
    6U, 5U, 4U, 2U, 2U, 1U, 0U, 0U, 0U, 0U, 0U, 0U,
    0U, 0U, 0U, 0U, 0U, 0U,
};

#endif // BLINKER_SEQ_H
