#!/usr/bin/env python3

from math import floor
from pathlib import Path


RISE_MS = 80
HOLD_MS = 160
FALL_MS = 320
GAP_MS = 100
TPS = 100

MIN = 0
MAX = 100
GAMMA = True

_GAMMA_EXPONENT = 2.0
_TIMEBASE_MS = 1000
_MAX_FRAME_COUNT = 65535
_VALUES_PER_LINE = 12

_OUTPUT_DIR = Path(__file__).resolve().parent
_HEADER_PATH = _OUTPUT_DIR / "blinker_seq.h"
_GRAPH_PATH = _OUTPUT_DIR / "blinker_seq.svg"


def _round_half_up(value: float) -> int:
    return floor(value + 0.5)


def _frame_at(timestamp_ms: int) -> int:
    return (timestamp_ms * TPS + (_TIMEBASE_MS // 2)) // _TIMEBASE_MS


def _settings_validate() -> None:
    durations = {
        "RISE_MS": RISE_MS,
        "HOLD_MS": HOLD_MS,
        "FALL_MS": FALL_MS,
        "GAP_MS": GAP_MS,
    }

    for name, duration_ms in durations.items():
        if isinstance(duration_ms, bool) or not isinstance(duration_ms, int):
            raise ValueError(f"{name} must be an integer")
        if duration_ms < 0:
            raise ValueError(f"{name} must not be negative")

    if RISE_MS == 0:
        raise ValueError("RISE_MS must be greater than zero")
    if FALL_MS == 0:
        raise ValueError("FALL_MS must be greater than zero")
    if GAP_MS == 0:
        raise ValueError("GAP_MS must be greater than zero")
    if isinstance(TPS, bool) or not isinstance(TPS, int) or not 1 <= TPS <= 1000:
        raise ValueError("TPS must be an integer between 1 and 1000")
    if isinstance(MIN, bool) or not isinstance(MIN, int) or not 0 <= MIN <= 255:
        raise ValueError("MIN must be an integer between 0 and 255")
    if isinstance(MAX, bool) or not isinstance(MAX, int) or not 0 <= MAX <= 255:
        raise ValueError("MAX must be an integer between 0 and 255")
    if MIN >= MAX:
        raise ValueError("MIN must be less than MAX")
    if not isinstance(GAMMA, bool):
        raise ValueError("GAMMA must be true or false")


def _segment_frames_get() -> dict[str, int]:
    rise_end = _frame_at(RISE_MS)
    hold_end = _frame_at(RISE_MS + HOLD_MS)
    fall_end = _frame_at(RISE_MS + HOLD_MS + FALL_MS)
    cycle_end = _frame_at(RISE_MS + HOLD_MS + FALL_MS + GAP_MS)

    frames = {
        "Rise": rise_end,
        "Hold": hold_end - rise_end,
        "Fall": fall_end - hold_end,
        "Gap": cycle_end - fall_end,
    }

    if frames["Rise"] == 0:
        raise ValueError("RISE_MS is shorter than one realized frame")
    if frames["Fall"] == 0:
        raise ValueError("FALL_MS is shorter than one realized frame")
    if frames["Gap"] == 0:
        raise ValueError("GAP_MS is shorter than one realized frame")
    if cycle_end > _MAX_FRAME_COUNT:
        raise ValueError(f"generated sequence exceeds {_MAX_FRAME_COUNT} frames")

    return frames


def _output_value_get(level: float) -> int:
    corrected_level = level**_GAMMA_EXPONENT if GAMMA else level
    return _round_half_up(MIN + ((MAX - MIN) * corrected_level))


def _sequence_generate(frames: dict[str, int]) -> tuple[list[int], int]:
    rise_end = frames["Rise"]
    hold_end = rise_end + frames["Hold"]
    fall_end = hold_end + frames["Fall"]
    frame_count = fall_end + frames["Gap"]
    sequence: list[int] = []

    for frame in range(frame_count):
        if frame < rise_end:
            level = frame / frames["Rise"]
            sequence.append(_output_value_get(level))
        elif frame < hold_end:
            sequence.append(MAX)
        elif frame < fall_end:
            progress = (frame - hold_end) / frames["Fall"]
            sequence.append(_output_value_get(1.0 - progress))
        else:
            sequence.append(0)

    peak_frame = rise_end

    if peak_frame >= len(sequence) or sequence[peak_frame] != MAX:
        raise ValueError("realized HOLD_MS or FALL_MS must contain a peak frame")

    return sequence, peak_frame


def _header_write(sequence: list[int], peak_frame: int) -> None:
    rows = []

    for start in range(0, len(sequence), _VALUES_PER_LINE):
        values = sequence[start : start + _VALUES_PER_LINE]
        rows.append("    " + ", ".join(f"{value}U" for value in values) + ",")

    content = "\n".join(
        [
            "/* Generated by curve_gen.py. */",
            "",
            "#if !defined(BLINKER_SEQ_H)",
            "#define BLINKER_SEQ_H",
            "",
            '#include "al.h"',
            "",
            f"#define BLINKER_SEQ_TPS        {TPS}U",
            f"#define BLINKER_SEQ_PEAK_FRAME {peak_frame}U",
            "",
            "static const u8 BLINKER_SEQ[] =",
            "{",
            *rows,
            "};",
            "",
            "#endif // BLINKER_SEQ_H",
            "",
        ]
    )

    _HEADER_PATH.write_text(content, encoding="utf-8")


def _graph_write(sequence: list[int], frames: dict[str, int]) -> None:
    width = 1200
    height = 650
    margin_l = 90
    margin_r = 40
    margin_t = 80
    margin_b = 80
    plot_w = width - margin_l - margin_r
    plot_h = height - margin_t - margin_b
    frame_count = len(sequence)
    cycle_ms = frame_count * _TIMEBASE_MS / TPS
    blink_hz = TPS / frame_count

    def x_get(frame: float) -> float:
        return margin_l + ((frame / frame_count) * plot_w)

    def y_get(value: float) -> float:
        return margin_t + plot_h - ((value / 255.0) * plot_h)

    path = [f"M {x_get(0):.2f} {y_get(sequence[0]):.2f}"]

    for frame in range(1, frame_count + 1):
        x = x_get(frame)
        path.append(f"H {x:.2f}")

        if frame < frame_count:
            path.append(f"V {y_get(sequence[frame]):.2f}")

    svg = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#ffffff"/>',
        f'<text x="{width / 2:.0f}" y="32" text-anchor="middle" font-family="sans-serif" font-size="22" font-weight="bold">Blinker sequence</text>',
        f'<text x="{width / 2:.0f}" y="57" text-anchor="middle" font-family="sans-serif" font-size="14" fill="#444444">{TPS} TPS · {blink_hz:.3f} Hz · gamma {"on" if GAMMA else "off"}</text>',
    ]

    for value in (0, 51, 102, 153, 204, 255):
        y = y_get(value)
        svg.append(f'<line x1="{margin_l}" y1="{y:.2f}" x2="{width - margin_r}" y2="{y:.2f}" stroke="#dddddd" stroke-width="1"/>')
        svg.append(f'<text x="{margin_l - 12}" y="{y + 5:.2f}" text-anchor="end" font-family="sans-serif" font-size="12" fill="#444444">{value}</text>')

    for tick in range(11):
        frame = frame_count * tick / 10
        x = x_get(frame)
        timestamp_ms = cycle_ms * tick / 10
        svg.append(f'<line x1="{x:.2f}" y1="{margin_t}" x2="{x:.2f}" y2="{height - margin_b}" stroke="#eeeeee" stroke-width="1"/>')
        svg.append(f'<text x="{x:.2f}" y="{height - margin_b + 24}" text-anchor="middle" font-family="sans-serif" font-size="12" fill="#444444">{timestamp_ms:.0f}</text>')

    boundaries = []
    cumulative_frames = 0

    for name, frame_count_segment in frames.items():
        segment_start = cumulative_frames
        cumulative_frames += frame_count_segment
        boundaries.append((name, segment_start, cumulative_frames))

    for name, start, end in boundaries:
        if start > 0:
            x = x_get(start)
            svg.append(f'<line x1="{x:.2f}" y1="{margin_t}" x2="{x:.2f}" y2="{height - margin_b}" stroke="#777777" stroke-width="1" stroke-dasharray="5 5"/>')

        label_x = x_get((start + end) / 2)
        svg.append(f'<text x="{label_x:.2f}" y="{margin_t + 20}" text-anchor="middle" font-family="sans-serif" font-size="13" fill="#333333">{name}</text>')

    svg.extend(
        [
            f'<line x1="{margin_l}" y1="{height - margin_b}" x2="{width - margin_r}" y2="{height - margin_b}" stroke="#222222" stroke-width="2"/>',
            f'<line x1="{margin_l}" y1="{margin_t}" x2="{margin_l}" y2="{height - margin_b}" stroke="#222222" stroke-width="2"/>',
            f'<path d="{" ".join(path)}" fill="none" stroke="#1261a0" stroke-width="3" stroke-linejoin="miter"/>',
            f'<text x="{width / 2:.0f}" y="{height - 20}" text-anchor="middle" font-family="sans-serif" font-size="14">Time (ms)</text>',
            f'<text x="22" y="{height / 2:.0f}" text-anchor="middle" font-family="sans-serif" font-size="14" transform="rotate(-90 22 {height / 2:.0f})">Output value</text>',
            "</svg>",
            "",
        ]
    )

    _GRAPH_PATH.write_text("\n".join(svg), encoding="utf-8")


def _diagnostics_print(frames: dict[str, int], frame_count: int) -> None:
    requested_ms = {
        "Rise": RISE_MS,
        "Hold": HOLD_MS,
        "Fall": FALL_MS,
        "Gap": GAP_MS,
    }
    requested_cycle_ms = sum(requested_ms.values())
    realized_cycle_ms = frame_count * _TIMEBASE_MS / TPS

    print("Requested versus realized timing")
    print(f"{'Segment':<10} {'Requested':>12} {'Realized':>12} {'Frames':>8}")

    for name in ("Rise", "Hold", "Fall", "Gap"):
        realized_ms = frames[name] * _TIMEBASE_MS / TPS
        print(
            f"{name:<10} "
            f"{requested_ms[name]:>9} ms "
            f"{realized_ms:>9.3f} ms "
            f"{frames[name]:>8}"
        )

    print(
        f"{'Cycle':<10} "
        f"{requested_cycle_ms:>9} ms "
        f"{realized_cycle_ms:>9.3f} ms "
        f"{frame_count:>8}"
    )
    print(f"Blink frequency: {TPS / frame_count:.6f} Hz")
    print(f"Header: {_HEADER_PATH}")
    print(f"Graph:  {_GRAPH_PATH}")


def main() -> None:
    try:
        _settings_validate()
        frames = _segment_frames_get()
        sequence, peak_frame = _sequence_generate(frames)
        _header_write(sequence, peak_frame)
        _graph_write(sequence, frames)
        _diagnostics_print(frames, len(sequence))
    except ValueError as error:
        raise SystemExit(f"curve_gen: {error}") from error


if __name__ == "__main__":
    main()
